views/user.py
from flask import Blueprint, session, render_template, flash, redirect, url_for, request
from models.user.user import User
from models.user.tasks import deliver_mail_verification_email
import models.user.user_error as UserErrors
from models.user.forms import LoginForm, RegistrationForm, MailVerifiedForm, PasswordResetForm, PasswordResetTriggerForm
from models.user.decorators import requires_login

users = Blueprint('users', __name__)


@users.route('/login', methods=['GET', 'POST'])
def login_user():
    form = LoginForm()
    if form.validate_on_submit():
        # email = request.form.get('email')
        # password = request.form.get('password')
        email = form.email.data
        password = form.password.data
        try:
            if User.login(email, password):
                session['email'] = email
                return redirect(url_for('home_page'))
        except UserErrors.UserError as e:
            session['email'] = None
            flash(e.message, 'danger')
    return render_template("login.html", form=form)


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(form.email.data, form.password.data, form.name.data, form.company.data)
        try:
            user.register_user()
            session['email'] = user.email
            flash('Sign up is complete, enjoy our services. \nAn E-mail address verification link has been sent to {0}.'.format(form.email.data), 'success')
            return redirect(url_for('users.mail_verification'))
        except UserErrors.UserAlreadyRegisteredError as e:
            flash(e.message, 'danger')
    return render_template('signup.html', form=form)


@users.route('/mail/verification', methods=['GET', 'POST'])
def mail_verification():
    email = session['email']
    user = User.find_by_email(email=email)
    mail_verification = user.serialize_token()
    deliver_mail_verification_email(email=email, mail_verification=mail_verification)
    return redirect(url_for('home_page'))


@users.route('mail/verified', methods=['GET', 'POST'])
def mail_verified():
    form = MailVerifiedForm(mail_verification=request.args.get('mail_verification'))
    if form.validate_on_submit():
        user = User.deserialize_token(request.form.get('mail_verification'))
        if user is None:
            flash('Your mail verification has expired or was tampered with.', 'danger')
            return redirect(url_for('users.login_user'))
        user.email_valid = True
        user.update_user()
        flash('Your E-mail address has been verified', 'success')
        return redirect(url_for('users.login_user'))

    return render_template('mail_verification.html', form=form)


@users.route('/logout')
@requires_login
def logout_user():
    session['email'] = None
    return redirect(url_for('home_page'))


@users.route('/reset', methods=['GET', 'POST'])
def password_reset_trigger():
    form = PasswordResetTriggerForm()

    if form.validate_on_submit():
        email = form.email.data
        try:
            user = User.find_by_email(email=email)
            reset_token = user.serialize_token()
            from models.user.tasks import deliver_password_reset_email
            deliver_password_reset_email(email, reset_token)
            flash('A password rest link has been sent to {0}.'.format(email), 'success')
            return redirect(url_for('users.login_user'))
        except UserErrors.UserError as e:
            flash(e.message, 'danger')
    return render_template('password_reset_trigger.html', form=form)


@users.route('/reset/reset', methods=['GET', 'POST'])
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))
    if form.validate_on_submit():
        user = User.deserialize_token(request.form.get('reset_token'))
        if user is None:
            flash('Your reset token has expired or was tampered with.', 'danger')
            return redirect(url_for('users.password_reset_trigger'))

        form.populate_obj(user)
        hashed_password = User(email='None', password=request.form.get('password')).password  # hack to encrypt a password. by running init
        user.password = hashed_password
        user.update_user()

        flash('Your password has been reset.', 'success')
        return redirect(url_for('users.login_user'))

    return render_template('password_reset.html', form=form)


@users.route('/settings')
@requires_login
def settings():
    return render_template('settings.html')


templates/macros/billing.html


{% macro card_expiring_warning(subs, card) -%}
  {% if subs.plan_status == 'active' and card.is_expiring %}
    <div class="alert alert-warning" role="alert">
      <div class="container">
        Your credit card is going to expire soon,
        <a href="{{ url_for('billing.update_payment_method') }}">
          please update it</a>
        .
      </div>
    </div>
  {% endif %}
{%- endmacro %}


{% macro plan(plan) -%}

  <div class="col-lg-4 col-md-12 mb-4">
    <div class="card">
      <div class="text-white pricing-card d-flex align-items-center rgba-indigo-strong py-3 px-2 rounded"><h4>{{ plan.name }}</h4></div>
      <div class="card-body">
        {{ caller () }}

        {% if session['email'] %}
          {% if subs %}
            {% if plan.id == subs.plan_type and subs.plan_status == 'active' %}
              <button class="btn aqua-gradient btn-block btn-rounded z-depth-1a" disabled>
                Current plan
              </button>
            {% else %}
              <a id="submit_{{ plan.id }}" name="submit_{{ plan.id }}" href="{{ url_for('billing.checkout', plan=plan.id) }}"
                      class="btn blue-gradient btn-block btn-rounded z-depth-1a" data-target="#modalPricingForm">
                <img src="{{ url_for('static', filename='assets/images/spinner.gif') }}"
                     class="spinner"
                     width="16" height="11" alt="Spinner"/>
                Change plan
              </a>
            {% endif %}
          {% else %}
            <a href="{{ url_for('billing.checkout', plan=plan.id) }}"
               class="btn blue-gradient btn-block btn-rounded z-depth-1a" data-target="#modalPricingForm">Continue</a>
          {% endif %}
        {% else %}
          <a href="{{ url_for('users.signup') }}"
             class="btn blue-gradient btn-block btn-rounded z-depth-1a">
            Sign up
          </a>
        {% endif %}

        <p class="small text-muted sm-margin-top text-center"><strong>
          ${{ plan.amount | format_currency }} / {{ plan.interval }} </strong>
        </p>
      </div>
    </div>
  </div>

{%- endmacro %}


{% macro coupon_data(coupon) -%}
  {% if coupon.amount_off %}
    {% set discount = '$' + coupon.amount_off | format_currency %}
  {% else %}
    {% set discount = coupon.percent_off | string + '%' %}
  {% endif %}
  {% if coupon.duration == 'forever' %}
    {% set label = 'It is saving you ' + discount + ' per month forever.' %}
  {% elif coupon.duration == 'once' %}
    {% set label = 'It saved you ' + discount + ' this month.' %}
  {% else %}
    {% set label = 'It is saving you ' + discount + ' for the next ' + coupon.duration_in_months | string + ' months.' %}
  {% endif %}

  {{ label }}
{%- endmacro %}


{% macro coupon_duration_tag_for(coupon) -%}
  {% if coupon.duration == 'forever' %}
    <span class="label label-success">Forever</span>
  {% elif coupon.duration == 'once' %}
    <span class="label label-warning">Once</span>
  {% else %}
    <span class="label label-info">
      {{ coupon.duration_in_months }} months
    </span>
  {% endif %}
{%- endmacro %}


{% macro coupon_expiration(coupon) -%}
  {% if coupon.redeem_by %}
    <time class="from-now"
          data-datetime="{{ coupon.redeem_by }}">
      {{ coupon.redeem_by }}
    </time>
  {% elif coupon.duration_in_months %}
    &mdash;
  {% else %}
    Never
  {% endif %}
{%- endmacro %}


{% macro coupon_redeemed(times_redeemed, max_redemptions) -%}
  {% set total = max_redemptions if max_redemptions else '&infin;' | safe %}
  {{ times_redeemed }} / {{ total }}
{%- endmacro %}


{% macro coupon_discount(amount_off, percent_off) -%}
  {% if amount_off %}
    ${{ amount_off | format_currency }}
  {% else %}
    {{ percent_off }}%
  {% endif %}
{%- endmacro %}


{% macro subscription_details(coupon) -%}
<blockquote class="blockquote bq-primary">
  <h2 class="bq-title">Subscription details</h2>

  {% if coupon %}
    <div class="alert alert-info alert-small">
      Coupon code <strong>{{ coupon.code }}</strong> is applied to your
      subscription.
    </div>
    <span class="small text-muted">
      {{ coupon_data(coupon) }}
    </span>
    <br class="sm-margin-bottom">
    <br class="sm-margin-bottom">
  {% endif %}
{%- endmacro %}


{% macro upcoming_invoice(invoice) -%}
<blockquote class="blockquote bq-success">
  {% if invoice == None %}

    <h3 class="bq-title">No upcoming payments</h3>
    <p>You are not currently subscribed, so there's nothing to see here.</p>
  {% else %}
    <table class="table table-striped sm-margin-bottom">
      <thead>
        <tr>
          <th>Subscription</th>
          <th>Description</th>
          <th>Next billing date</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ invoice.plan }}</td>
          <td>{{ invoice.description }}</td>
          <td>
            <time class="short-date" data-datetime="{{ invoice.next_bill_on }}">
              {{ invoice.next_bill_on }}
            </time>
          </td>
          <td>
            ${{ invoice.amount_due | format_currency }}
            <span class="color--muted"> / {{ invoice.interval }}</span>
          </td>
        </tr>
      </tbody>
    </table>

  {% endif %}
    </blockquote>
{%- endmacro %}


{% macro invoices(invoices) -%}
  <h3>Recent billing history</h3>
  {% if invoices.count() == 0 %}
    <h4>No invoices found</h4>
    <p>This isn't an error. You just haven't been invoiced yet.</p>
  {% else %}
    <table class="table table-striped sm-margin-bottom">
      <thead>
        <tr>
          <th>Date</th>
          <th>Method</th>
          <th>Description</th>
          <th>Service period</th>
          <th>Tax</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
      {% for invoice in invoices %}
        <tr>
          <td>
            <time class="from-now" data-datetime="">
                {{ moment(invoice.created_on).format('YYYY-MM-DD hh:mm:ss') }}
            </time>
              </td>

          <td class="small">
            {{ invoice.brand }} ****{{ invoice.last4 }}
          </td>
          <td class="small">{{ invoice.description }}</td>
          <td>
            <time class="short-date" data-datetime="{{ invoice.period_start_on }}">
              {{ invoice.period_start_on }}
            </time>
            <span class="text-info">&mdash;</span>
            <time class="short-date" data-datetime="{{ invoice.period_end_on }}">
              {{ invoice.period_end_on }}
            </time>
          </td>
          <td title="{{ (invoice.tax_percent | round(2)) | string + '%' if invoice.tax_percent }}">
            {{ '$' + invoice.tax | format_currency if invoice.tax }}
          </td>
          <td title="{{ invoice.currency }}">
            ${{ invoice.total | format_currency }}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% endif %}
{%- endmacro %}

templates/macros/flash.html
{# Render Flask messages. #}
{%- macro render() -%}
  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      <div id="flash-messages" class="row sm-margin-top">
        {% for category, msg in messages %}
          <div class="alert alert-{{ category }}" role="alert">
            {{ msg }}
          </div>
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
{%- endmacro -%}

templates/macros/form.html
{# Render a form field's label with visual aid to see if it's required. #}
{%- macro field_label(f) -%}
  <label for="{{ f.id }}">
    {%- if f.flags.required -%}
      <strong>{{ f.label.text }}</strong>
    {%- else %}
      {{ f.label.text }}
    {%- endif %}
  </label>
{%- endmacro -%}


{# Render a form field's errors. #}
{%- macro field_errors(f) -%}
  {% if f.errors %}
    <ul class="list-unstyled text-danger field-error">
      {% for error in f.errors %}
          <li>{{ error | e }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{%- endmacro -%}


{# Render a form field. #}
{%- macro field(f, css_class='form-control') -%}
  {{ f(class=css_class, **kwargs) }}
{%- endmacro -%}


{# Render a checkbox field. #}
{%- macro checkbox_field(f) -%}
  {{ f(type='checkbox', **kwargs) }} {{ f.label }}
{%- endmacro -%}


{# Render a form group with errors for various field types. #}
{%- macro form_group(f, css_class='') -%}
  {% if f.errors %}
    {% set css_class = css_class + ' has-error ' + kwargs.pop('class', '') %}
  {% endif %}

  {% if f.type == 'BooleanField' %}
      <div class="checkbox {{ css_class }}">
    {{ checkbox_field(f, **kwargs) }}
  {% else %}
      <div class="form-group {{ css_class }}">
    {{ field_label(f) }}
    {{ field(f, **kwargs) }}
  {% endif %}

    {{ field_errors(f) }}
    {{ caller () }}
  </div>
{%- endmacro %}


{# Render a form tag that contains a CSRF token and all hidden fields. #}
{%- macro form_tag(endpoint, fid='', css_class='', method='post') -%}
  <form action="{{ url_for(endpoint, **kwargs) }}" method="{{ method }}"
        id="{{ fid }}" class="{{ css_class }}" role="form">
    {{ form.hidden_tag() }}
    {{ caller () }}
  </form>
{%- endmacro -%}